blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blogs'),
    path('<int:pk>/', views.BlogDetailView.as_view(), name='blog-detail'),
    path('bloggers/', views.BloggerListView.as_view(), name='bloggers'),
    path('blogger/<int:pk>', views.BlogsByAuthorListView.as_view(), name='blog-by-author'),
    path('<int:pk>/comment',views.add_comment_to_blog, name='add-comment'),
    path('delete/<int:comment_id>',views.delete_comment, name='delete-comment'),
]


# primary key 1 of blog is not available because I deleted the first blog before. need to resolve this problem later

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup_user, name='signup'),
]

simple/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    ]

blog/models.py
from django.db import models
from datetime import date
from django.urls import reverse
from django.contrib.auth.models import User

class BlogAuthor(models.Model):
    "Model representing author of a blog"
    name = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=400, help_text="Update your bio here.")

    class Meta:
        ordering = ['name', 'bio']

    def get_absolute_url(self):
        return reverse('blogs-by-author')

    def __str__(self):
        return self.name.username


class Blog(models.Model):
    "Model representing a blog post"
    title = models.CharField(max_length=100)
    description = models.TextField()
    author = models.ForeignKey(BlogAuthor, on_delete=models.SET_NULL, null=True)
    post_date = models.DateField(default=date.today)
    likes = models.IntegerField(default=0)

    class Meta:
        ordering = ['-post_date']

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog instance.
        """
        return reverse('blog-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title


class BlogComment(models.Model):
    "Model for representing comments of a blog post"
    description = models.TextField(max_length=1000, help_text="Enter your comment here.")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
      # Foreign Key used because BlogComment can only have one author/User, but users can have multiple comments
    post_date = models.DateTimeField(auto_now_add=True)
    blog= models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-post_date']

    def __str__(self):
        return self.description

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from django.views import generic
from .models import Blog, BlogAuthor, BlogComment
from django.contrib.auth.models import User

from .form import CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import auth

def index(request):
    return render(request, 'blog/index.html')


class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 4
    # template_name = 'blogs/blog_list.html'

class BlogDetailView(generic.DetailView):
    """
    Generic class-based detail view for a blog.
    """
    model = Blog
    context_object_name = 'blog_post'
    # template_name = 'blog/blog_post.html'


class BloggerListView(generic.ListView):
    model = BlogAuthor
    paginate_by = 5


class BlogsByAuthorListView(generic.ListView):
    """
    View for a list of blogs posted by a particular blogger
    """
    model = Blog
    paginate_by = 5
   # template_name = 

    def get_queryset(self):
        """
        Return list of Blog objects created by BlogAuthor
        """
        id = self.kwargs['pk']
        by_author = get_object_or_404(BlogAuthor, pk=id)
        return Blog.objects.filter(author=by_author)

    def get_context_data(self, **kwargs):
        """
        Add BlogAuthor to context so they can be displayed in the template
        """
        context = super(BlogsByAuthorListView, self).get_context_data(**kwargs)
        context['blogger'] = get_object_or_404(BlogAuthor, pk=self.kwargs['pk'])
        return context


@login_required(login_url='login')
def add_comment_to_blog(request, pk):
    post = get_object_or_404(Blog, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.blog = post
            comment.author = auth.get_user(request)
            comment.save()
            return redirect('blog-detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_blog.html', {'form': form})



def delete_comment(request, comment_id):
    comment = get_object_or_404(BlogComment, pk=comment_id)
    blog_id = comment.blog.id
    if comment.author == request.user:
        comment.delete()
    return redirect('blog-detail', blog_id)

home/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from .form import SignUpForm

# do this later after creating models for home page ie models for training courses
#class IndexView(generic)

def index(request):
    return render(request, 'home/index.html', {})
    


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        print(user)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.error(request, ('Error in logging in.. please try again!'))
            return redirect('login')
    else:
        return render(request, 'authenticate/login.html', {})

def logout_user(request):
    logout(request)
    messages.success(request, ('You have been successfully logged out!'))
    return redirect('login')

def signup_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            # username = form.cleaned_data['username']
            # password = form.cleaned_data['password1']
            # user = authenticate(username=username, password = password)
            # login(request, user)
            messages.success(request, ('You have successfully Signed up!!'))
            return redirect('login')
        else:
            messages.error(request, ('Your form is not validated! Try again!!'))
            return redirect('signup')

    else:
        form = SignUpForm()
    context = {'form':form}
    return render(request, 'authenticate/signup.html', context)

blog/templates/blog/add_comment_to_blog.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>New comment</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Send</button>
        </form>
    </div>
{% endblock %}
{% block footerrow1%}
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/blog_list.html' %}
{% load static %}

<title>{% block title %}Blog Post{% endblock %}</title>

{% block heroarea %}
	<!-- Hero-area -->
	<div class="hero-area section">

		<!-- Backgound Image -->
		<div class="bg-image bg-parallax overlay" style="background-image:url({% static 'blog/img/blog-post-background.jpg' %})"></div>
		<!-- /Backgound Image -->

		<div class="container">
			<div class="row">
				<div class="col-md-10 col-md-offset-1 text-center">
					<ul class="hero-area-tree">
						<li><a href="index.html">Home</a></li>
						<li><a href="blog.html">Blog</a></li>
						<li>{{ blog_post.title }}</li>
					</ul>
					<h1 class="white-text">{{ blog_post.title }}</h1>
					<ul class="blog-post-meta">
						<li class="blog-meta-author">By : <a href="#">{{ blog_post.author }}</a></li>
						<li>{{ blog_post.post_date }}</li>
						<li class="blog-meta-comments"><a href="#"><i class="fa fa-comments"></i> {{blog_post.blogcomment_set.count}}</a></li>
					</ul>
				</div>
			</div>
		</div>

	</div>
	<!-- /Hero-area -->
{% endblock %}


{% block mainblog %}
<!-- main blog -->
<div id="main" class="col-md-9">

	<!-- blog post -->
	<div class="blog-post">
		{{ blog_post.description }}
	</div>
	<!-- /blog post -->

	<!-- blog share -->
	<div class="blog-share">
		<h4>Share This Post:</h4>
		<a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
		<a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
		<a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
	</div>
	<!-- /blog share -->

	<!-- blog comments -->
	<div class="blog-comments">
		<h3>{{ blog_post.blogcomment_set.count }} Comments</h3>
		
		{% if user.is_authenticated %}
			<a type="button" class="btn btn-primary" href="{% url 'add-comment' pk=blog_post.pk %}">Post Comment</a>
		{% else %}
			<a type="button" class="btn btn-primary" href="{% url 'login' %}">Login to add comment</a>
		{% endif %}

		{% for comment in blog_post.blogcomment_set.all %}
		<!-- single comment -->
		<div class="media">
			<div class="media-left">
				<img src="{% static 'blog/img/avatar.png' %}" alt="">
			</div>
			<div class="media-body">
				<h4 class="media-heading">{{ comment.author }}</h4>
				<p>{{ comment.description }}</p>
				<div class="date-reply"><span>{{ comment.post_date }}</span><a href="#" class="reply">Reply</a>{% if comment.author == request.user%}<a href="{% url 'delete-comment' comment.id %}" class="comment-delete">Delete</a> {% endif %}</div>
			</div>

			<!-- comment reply -->
			<div class="media">
				<div class="media-left">
					<img src="./img/avatar.png" alt="">
				</div>
				<div class="media-body">
					<h4 class="media-heading">John Doe</h4>
					<p>Cu his iudico appareat ullamcorper, at mea ignota nostrum. Nonumy argumentum id cum, eos adversarium contentiones id</p>
					<div class="date-reply"><span>Oct 18, 2017 - 4:00AM</span><a href="#" class="reply">Reply</a></div>
				</div>
			</div>
			<!-- /comment reply -->

			<!-- comment reply -->
			<div class="media">
				<div class="media-left">
					<img src="./img/avatar.png" alt="">
				</div>
				<div class="media-body">
					<h4 class="media-heading">John Doe</h4>
					<p>Cu his iudico appareat ullamcorper, at mea ignota nostrum. Nonumy argumentum id cum, eos adversarium contentiones id</p>
					<div class="date-reply"><span>Oct 18, 2017 - 4:00AM</span><a href="#" class="reply">Reply</a></div>
				</div>
			</div>
			<!-- /comment reply -->

		</div>
		<!-- /single comment -->
		{% endfor %}

	</div>
	<!-- /blog comments -->
</div>
<!-- /main blog -->
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Blog Lists{% endblock %}</title>
{% block content %}
	{% block heroarea %}
		<!-- Hero-area -->
		<div class="hero-area section">

			<!-- Backgound Image -->
			<div class="bg-image bg-parallax overlay" style="background-image:url({% static 'blog/img/page-background.jpg' %})"></div>
			<!-- /Backgound Image -->

			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1 text-center">
						<ul class="hero-area-tree">
							<li><a href="{% url 'index' %}">Home</a></li>
							<li>Blog</li>
						</ul>
						<h1 class="white-text">Blog Page</h1>

					</div>
				</div>
			</div>

		</div>
		<!-- /Hero-area -->
	{% endblock %}
	{% block blog %}
		<!-- Blog -->
		<div id="blog" class="section">

			<!-- container -->
			<div class="container">
				<!--show only there exist at least one blog-->
				<!-- row -->
				<div class="row">

					{% block mainblog %}
						{% if blog_list %}
							<!-- main blog -->
							<div id="main" class="col-md-9">

								<!-- row -->
								<div class="row">

									{% for blog in blog_list %}
									<!-- single blog -->
									<div class="col-md-6">
										<div class="single-blog">
											<div class="blog-img">
												<a href="{% url 'blog-detail' blog.pk %}">
													<img src="{% static 'blog/img/blog01.jpg' %}" alt="">
												</a>
											</div>
											<h4><a href="{% url 'blog-detail' blog.pk %}">{{ blog.title }}</a></h4>
											<div class="blog-meta">
												<span class="blog-meta-author">By: <a href="#">{{ blog.author }}</a></span>
												<div class="pull-right">
													<span>{{ blog.post_date }}</span>
													<span class="blog-meta-comments"><a href="#"><i class="fa fa-comments"></i> {{ blog.blogcomment_set.count }}</a></span>
												</div>
											</div>
										</div>
									</div>
									<!-- /single blog -->
									{% endfor %}

								</div>
								<!-- /row -->

								<!-- row -->
								<div class="row">

									{% if is_paginated %}
									<!-- pagination -->
									<div class="col-md-12">
										<div class="post-pagination">
											{% if page_obj.has_previous %}
												<a href="?page={{ page_obj.previous_page_number }}" class="pagination-back pull-left">Previous</a>
											{% endif %}
											{% for num in page_obj.paginator.page_range %}
												<ul class="pages">
												{% if page_obj.number == num %}
													<li class="active" href="?page={{ num }}">{{ num }}</li>
												{% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2'%}
												<li><a href="?page={{ num }}">{{ num }}</a></li>
												{% endif%}
												</ul>
											{% endfor %}
											<!-- <ul class="pages">
												<li class="active">1</li>
												<li><a href="#">2</a></li>
												<li><a href="#">3</a></li>
												<li><a href="#">4</a></li>
											</ul> -->
											{% if page_obj.has_next %}
												<a href="?page={{ page_obj.next_page_number }}" class="pagination-next pull-right">Next</a>
											{% endif %}
										</div>
									</div>
									<!-- pagination -->
									{% endif %}

								</div>
								<!-- /row -->
							</div>
							<!-- /main blog -->
						{% else %}
							<h1>There are no blogs.</h1>
						{% endif %}
					{% endblock %}

					{% block asideblog %}
						<!-- aside blog -->
						<div id="aside" class="col-md-3">

							<!-- search widget -->
							<div class="widget search-widget">
								<form>
									<input class="input" type="text" name="search">
									<button><i class="fa fa-search"></i></button>
								</form>
							</div>
							<!-- /search widget -->

							<!-- category widget -->
							<div class="widget category-widget">
								<h3>Categories</h3>
								<a class="category" href="#">Web <span>12</span></a>
								<a class="category" href="#">Css <span>5</span></a>
								<a class="category" href="#">Wordpress <span>24</span></a>
								<a class="category" href="#">Html <span>78</span></a>
								<a class="category" href="#">Business <span>36</span></a>
							</div>
							<!-- /category widget -->

							<!-- posts widget -->
							<div class="widget posts-widget">
								<h3>Recents Posts</h3>

								<!-- single posts -->
								<div class="single-post">
									<a class="single-post-img" href="blog-post.html">
										<img src="{% static 'blog/img/post01.jp' %}g" alt="">
									</a>
									<a href="blog-post.html">Pro eu error molestie deserunt.</a>
									<p><small>By : John Doe .18 Oct, 2017</small></p>
								</div>
								<!-- /single posts -->

								<!-- single posts -->
								<div class="single-post">
									<a class="single-post-img" href="blog-post.html">
										<img src="{% static 'blog/img/post02.jpg' %}" alt="">
									</a>
									<a href="blog-post.html">Pro eu error molestie deserunt.</a>
									<p><small>By : John Doe .18 Oct, 2017</small></p>
								</div>
								<!-- /single posts -->

								<!-- single posts -->
								<div class="single-post">
									<a class="single-post-img" href="blog-post.html">
										<img src="{% static 'blog/img/post03.jpg' %}" alt="">
									</a>
									<a href="blog-post.html">Pro eu error molestie deserunt.</a>
									<p><small>By : John Doe .18 Oct, 2017</small></p>
								</div>
								<!-- /single posts -->

							</div>
							<!-- /posts widget -->

							<!-- tags widget -->
							<div class="widget tags-widget">
								<h3>Tags</h3>
								<a class="tag" href="#">Web</a>
								<a class="tag" href="#">Photography</a>
								<a class="tag" href="#">Css</a>
								<a class="tag" href="#">Responsive</a>
								<a class="tag" href="#">Wordpress</a>
								<a class="tag" href="#">Html</a>
								<a class="tag" href="#">Website</a>
								<a class="tag" href="#">Business</a>
							</div>
							<!-- /tags widget -->
						</div>
						<!-- /aside blog -->
					{% endblock %}
				</div>
				<!-- row -->
			</div>
			<!-- container -->
		</div>
		<!-- /Blog -->
	{% endblock %}
{% endblock %}

home/templates/authenticate/login.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    {% block alert %}
    {% if messages %}
      {% for message in messages %}
          <div class="alert alert-warning alert-dismissible" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
      {% endfor %}
    {% endif %}
    {% endblock %}
    <div class="col-md-6 col-md-offset-3">
        <h2 class="col-sm-offset-3 col-sm-10">Login</h2>
        <form class="form-horizontal" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <div class="col-sm-10">
                <input type="text" class="form-control" name="username" placeholder="Enter Username">
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10">
                <input type="password" class="form-control" name="password" placeholder="Password">
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10">
                <button type="submit" class="main-button icon-button">Login</button>
              </div>
            </div>
          </form>
    </div>
  </div>
{% endblock %}

{% block footerrow1%}
{% endblock %}

home/templates/authenticate/signup.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="col-md-6 col-md-offset-3">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
            <h2 class="col-sm-offset-4 col-sm-10"> Sign Up</h2>
            <form method="POST" action="{% url 'signup' %}">
                {% csrf_token %}
                <!-- {% if form.errors %}
                    <p>Form contains error</p>
                {% endif %} -->
                {{ form }}
                <br>
                <button type="submit" class="main-button icon-button">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}
{% block footerrow1 %}
{% endblock %}

home/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>{% block title %}Home Page{% endblock %}</title>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Lato:700%7CMontserrat:400,600" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}"/>

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static 'home/css/style.css' %}"/>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
  </head>
  <body>
    
    <!-- Header -->
    <header id="header">
        <div class="container">

            <div class="navbar-header">
                <!-- Logo -->
                <div class="navbar-brand">
                    <a class="logo" href="{% url 'index' %}">
                        <img src="{% static 'home/img/logo.png' %}" alt="logo">
                    </a>
                </div>
                <!-- /Logo -->

                <!-- Mobile toggle -->
                <button class="navbar-toggle">
                    <span></span>
                </button>
                <!-- /Mobile toggle -->
            </div>

            <!-- Navigation -->
            <nav id="nav">
                <ul class="main-menu nav navbar-nav navbar-right">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Courses</a></li>
                    <li><a href="{% url 'blogs' %}">Blog</a></li>
                    <li><a href="contact.html">Contact</a></li>
                    {% if user.is_authenticated %}
                        <li><a class="btn btn-default" href="{% url 'logout' %}" role="button">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                        <li><a class="btn btn-default" href="{% url 'signup' %}" role="button">Sign Up</a></li>
                    {% endif %}
                </ul>
            </nav>
            <!-- /Navigation -->

        </div>
    </header>
    <!-- /Header -->

    {% block content %}
    {% endblock %}

    <!-- Footer -->
    <footer id="footer" class="section">

        <!-- container -->
        <div class="container">
            
            {% block footerrow1 %}
            <!-- row -->
            <div class="row">

                <!-- footer logo -->
                <div class="col-md-6">
                    <div class="footer-logo">
                        <a class="logo" href="{% url 'index' %}">
                            <img src="{% static 'home/img/logo.png' %}" alt="logo">
                        </a>
                    </div>
                </div>
                <!-- footer logo -->

                <!-- footer nav -->
                <div class="col-md-6">
                    <ul class="footer-nav">
                        <li><a href="index.html">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Courses</a></li>
                        <li><a href="blog.html">Blog</a></li>
                        <li><a href="contact.html">Contact</a></li>
                    </ul>
                </div>
                <!-- /footer nav -->

            </div>
            <!-- /row -->
            {% endblock %}

            <!-- row -->
            <div id="bottom-footer" class="row">

                <!-- social -->
                <div class="col-md-4 col-md-push-8">
                    <ul class="footer-social">
                        <li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#" class="instagram"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#" class="youtube"><i class="fa fa-youtube"></i></a></li>
                        <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
                <!-- /social -->

                <!-- copyright -->
                <div class="col-md-8 col-md-pull-4">
                    <div class="footer-copyright">
                        <span>&copy; Copyright 2018. All Rights Reserved. | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com">Colorlib</a></span>
                    </div>
                </div>
                <!-- /copyright -->

            </div>
            <!-- row -->

        </div>
        <!-- /container -->

    </footer>
    <!-- /Footer -->

    <!-- preloader -->
    <div id='preloader'><div class='preloader'></div></div>
    <!-- /preloader -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- jQuery Plugins -->
    <script type="text/javascript" src="{% static 'home/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'home/js/main.js' %}"></script>

  </body>
</html>